import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfExportService {
  static Future<Uint8List> generatePdf({
    required String title,
    String? subjectName,
    DateTime? recordingDate,
    Duration? duration,
    required String summaryMarkdown,
    String? transcriptMarkdown,
    bool includeTranscript = false,
  }) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(
        base: pw.Font.helvetica(),
        bold: pw.Font.helveticaBold(),
      ),
    );

    final mainColor = PdfColor.fromHex('#818CF8');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        header: (context) => _buildHeader(
          title: title,
          subjectName: subjectName,
          recordingDate: recordingDate,
          duration: duration,
          mainColor: mainColor,
        ),
        footer: (context) => _buildFooter(context),
        build: (context) {
          final widgets = <pw.Widget>[];

          widgets.addAll(_parseMarkdown(summaryMarkdown, mainColor));

          if (includeTranscript &&
              transcriptMarkdown != null &&
              transcriptMarkdown.isNotEmpty) {
            widgets.add(pw.NewPage());
            widgets.add(
              pw.Text(
                'Full Transcript',
                style: pw.TextStyle(
                  fontSize: 18,
                  fontWeight: pw.FontWeight.bold,
                  color: mainColor,
                ),
              ),
            );
            widgets.add(pw.SizedBox(height: 10));
            widgets.addAll(
              _parseMarkdown(transcriptMarkdown, mainColor, isTranscript: true),
            );
          }

          return widgets;
        },
      ),
    );

    return pdf.save();
  }

  static pw.Widget _buildHeader({
    required String title,
    String? subjectName,
    DateTime? recordingDate,
    Duration? duration,
    required PdfColor mainColor,
  }) {
    final dateStr = recordingDate != null
        ? '${recordingDate.year}-${recordingDate.month.toString().padLeft(2, '0')}-${recordingDate.day.toString().padLeft(2, '0')}'
        : null;

    final durationStr = duration != null ? '${duration.inMinutes} min' : null;

    final meta = [
      if (subjectName != null && subjectName.isNotEmpty) subjectName,
      if (dateStr != null) dateStr,
      if (durationStr != null) durationStr,
    ].join(' | ');

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Lecto',
          style: pw.TextStyle(
            fontSize: 28,
            fontWeight: pw.FontWeight.bold,
            color: mainColor,
          ),
        ),
        pw.SizedBox(height: 8),
        pw.Text(
          title,
          style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
        ),
        if (meta.isNotEmpty) ...[
          pw.SizedBox(height: 4),
          pw.Text(
            meta,
            style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
          ),
        ],
        pw.SizedBox(height: 12),
        pw.Divider(color: PdfColors.grey400),
        pw.SizedBox(height: 12),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      alignment: pw.Alignment.centerRight,
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Text(
        'Generated by Lecto - Page ${context.pageNumber} of ${context.pagesCount}',
        style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey500),
      ),
    );
  }

  static List<pw.Widget> _parseMarkdown(
    String text,
    PdfColor mainColor, {
    bool isTranscript = false,
  }) {
    final lines = text.split('\n');
    final widgets = <pw.Widget>[];

    List<List<String>> currentTable = [];

    void flushTable() {
      if (currentTable.isNotEmpty) {
        widgets.add(
          pw.TableHelper.fromTextArray(
            data: currentTable,
            border: pw.TableBorder.all(color: PdfColors.grey400),
            cellAlignment: pw.Alignment.centerLeft,
            cellPadding: const pw.EdgeInsets.all(4),
          ),
        );
        widgets.add(pw.SizedBox(height: 8));
        currentTable = [];
      }
    }

    for (int i = 0; i < lines.length; i++) {
      String line = lines[i].trim();

      // If line is empty, skip, but flush table
      if (line.isEmpty) {
        flushTable();
        widgets.add(pw.SizedBox(height: 4));
        continue;
      }

      // Check for table
      if (line.startsWith('|') && line.endsWith('|')) {
        final cells = line
            .split('|')
            .skip(1)
            .map((e) => e.trim())
            .toList();
        if (cells.isNotEmpty) {
          cells.removeLast(); // skip last empty due to trailing |
          
          // skip separator lines like |---|---|
          if (cells.every((cell) => cell.replaceAll('-', '').isEmpty)) {
            continue;
          }

          currentTable.add(cells);
        }
        continue;
      } else {
        flushTable();
      }

      // Check headings
      if (line.startsWith('# ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 12, bottom: 4),
            child: pw.Text(
              line.substring(2),
              style: pw.TextStyle(
                fontSize: 18,
                fontWeight: pw.FontWeight.bold,
                color: mainColor,
              ),
            ),
          ),
        );
        continue;
      }
      if (line.startsWith('## ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 10, bottom: 4),
            child: pw.Text(
              line.substring(3),
              style: pw.TextStyle(
                fontSize: 15,
                fontWeight: pw.FontWeight.bold,
                color: mainColor,
              ),
            ),
          ),
        );
        continue;
      }
      if (line.startsWith('### ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 8, bottom: 4),
            child: pw.Text(
              line.substring(4),
              style: pw.TextStyle(
                fontSize: 13,
                fontWeight: pw.FontWeight.bold,
                color: mainColor,
              ),
            ),
          ),
        );
        continue;
      }

      // Check blockquote
      if (line.startsWith('> ')) {
        widgets.add(
          pw.Container(
            margin: const pw.EdgeInsets.symmetric(vertical: 4),
            padding: const pw.EdgeInsets.only(left: 8),
            decoration: pw.BoxDecoration(
              border: pw.Border(
                left: pw.BorderSide(color: mainColor, width: 2),
              ),
            ),
            child: _parseRichText(
              line.substring(2),
              fontSize: isTranscript ? 10 : 11,
            ),
          ),
        );
        continue;
      }

      // Check checkbox
      if (line.startsWith('- [ ] ') ||
          line.startsWith('- [x] ') ||
          line.startsWith('* [ ] ') ||
          line.startsWith('* [x] ')) {
        final isChecked = line.contains('[x]');
        final textPart = line.substring(6);
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 2),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Container(
                  margin: const pw.EdgeInsets.only(top: 2, right: 6),
                  width: 10,
                  height: 10,
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.black, width: 1),
                    color: isChecked ? PdfColors.black : PdfColors.white,
                  ),
                ),
                pw.Expanded(
                  child: _parseRichText(
                    textPart,
                    fontSize: isTranscript ? 10 : 11,
                  ),
                ),
              ],
            ),
          ),
        );
        continue;
      }

      // Check bullet
      if (line.startsWith('- ') || line.startsWith('* ')) {
        widgets.add(
          pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 2, horizontal: 8),
            child: pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Padding(
                  padding: const pw.EdgeInsets.only(top: 4, right: 6),
                  child: pw.Container(
                    width: 4,
                    height: 4,
                    decoration: const pw.BoxDecoration(
                      color: PdfColors.black,
                      shape: pw.BoxShape.circle,
                    ),
                  ),
                ),
                pw.Expanded(
                  child: _parseRichText(
                    line.substring(2),
                    fontSize: isTranscript ? 10 : 11,
                  ),
                ),
              ],
            ),
          ),
        );
        continue;
      }

      // Regular paragraph
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 4),
          child: _parseRichText(line, fontSize: isTranscript ? 10 : 11),
        ),
      );
    }

    flushTable();

    return widgets;
  }

  static pw.Widget _parseRichText(String text, {double fontSize = 11}) {
    final parts = text.split('**');
    if (parts.length == 1) {
      return pw.Text(text, style: pw.TextStyle(fontSize: fontSize));
    }

    final spans = <pw.InlineSpan>[];
    for (int i = 0; i < parts.length; i++) {
      if (parts[i].isEmpty) continue;
      if (i % 2 == 1) {
        // bold
        spans.add(
          pw.TextSpan(
            text: parts[i],
            style: pw.TextStyle(
              fontWeight: pw.FontWeight.bold,
              fontSize: fontSize,
            ),
          ),
        );
      } else {
        // normal
        spans.add(
          pw.TextSpan(
            text: parts[i],
            style: pw.TextStyle(fontSize: fontSize),
          ),
        );
      }
    }

    return pw.RichText(text: pw.TextSpan(children: spans));
  }

  static String generateFilename({
    String? subjectName,
    DateTime? date,
    String? title,
  }) {
    final parts = ['Lecto'];
    if (subjectName != null && subjectName.isNotEmpty) {
      parts.add(subjectName.replaceAll(' ', ''));
    }
    if (date != null) {
      parts.add(
        '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}',
      );
    }
    if (title != null && title.isNotEmpty) {
      parts.add(title.replaceAll(' ', ''));
    }
    return '${parts.join('_')}.pdf';
  }

  static Future<void> sharePdf(Uint8List pdfBytes, String filename) async {
    await Printing.sharePdf(bytes: pdfBytes, filename: filename);
  }
}
